import Header from "./components/Header";

export const metadata = {
  title: "AvatarUI",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: "#100f0f" }}>
        <Header />
        {children}
      </body>
    </html>
  );
}
