export const metadata = {
  title: "AvatarUI",
  description: "Generated by Next.js",
};

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={inter.className}>
      <body style={{ backgroundColor: "#100f0f" }}>{children}</body>
    </html>
  );
}
